### ISSUE TITLE
Hover over @ConfigProperty name should resolve property expressions

### ISSUE THREAD

**Issue by fbricon** [eclipse/lsp4mp#101]
Given this application.properties:
```properties
quarkus.application.name=My App
greeting=Welcome to ${quarkus.application.name}
```
hovering over the "greeting" key, "Welcome to My App" is displayed, as expected.

In a class that declares
```java
@Inject
@ConfigProperty(name="greeting")
String greeting;
```
hovering over the `greeting` value of @ConfigProperty, "Welcome to ${quarkus.application.name}" is displayed, instead of the resolved "Welcome to My App"

See https://youtu.be/0KYL6Q1QO4c?t=1677

**Comment by angelozerr** [comment]
Please note that when you hover ConfigProperty in Java file, we use the properties file from `target `folder. This issue requires that evaluation expression must be done in MP JDT LS side.

Today evaluation expression is done only on MP LS side. It should be nice to share this evaludation expression utility between MP JDT LS and MP LS side.

We have the same classes in commons package:

 * on MP JDT LS side: https://github.com/eclipse/lsp4mp/tree/master/microprofile.jdt/org.eclipse.lsp4mp.jdt.core/src/main/java/org/eclipse/lsp4mp/commons

 * on MP LS side: https://github.com/eclipse/lsp4mp/tree/master/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/commons

This evaluate expression utility should be stored in this commons/utils package for instance. We did a copy/paste from those classes because it's hard to have a new project which works with OSGi and without OSGi, but perhaps it's time to do that.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lsp4mp/pull/283
