### ISSUE TITLE
Language Server attempts to calculate CodeAction for stale diagnostics

### ISSUE THREAD

**Issue by datho7561** [eclipse/lsp4mp#272]
In https://github.com/eclipse/lsp4mp/commit/1d0377596b08e453c609bf5d0a0451af553a1e32, we delay revalidating a file, which means that we delay pushing new diagnostics until the user stops modifying the document, leaving stale diagnostics in the document.

However, according to the LSP, https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeActionContext, the client is free to request code actions to address these diagnostics, even after edits have been made to the document that might make them no longer relevant.

This is an issue, since our code to generate CodeActions currently assumes that the diagnostics it receives from the client are applicable to the current state of the document. When this assumption doesn't hold, bad CodeActions may be generated, or CodeAction generation may fail with an Exception. For instance, given this property file:

```properties
invalid.property|=value
```

If you press backspace with your cursor at the `|`, when you delete the last remaining `i` of `invalid.property`, an Exception will occur, since the language server will attempt to calculate the CodeAction to ignore the fact that the property `i` doesn't exist, however the property `i` is no longer present in the document.

We need some strategy to avoid calculating CodeActions when the diagnostics that are sent from the client don't match up with the current state of the document.

**Comment by rgrunber** [comment]
CC'ing @testforstephen here for awareness. Basically, we discovered a bug for LSP4MP where code actions use stale diagnostics.

I was able to reproduce this in JDT-LS also but I'm not aware of this causing major problems. I think this is because even though the diagnostic is stale, in most cases we only extract the problem ID (defined by JDT Core) and so any code actions returned are never used as the diagnostics they're associated with disappear. I did find this though :

(The code action normally isn't suggested because it creates a compilation error)
![stale-diagnostic-codeaction-bug](https://user-images.githubusercontent.com/1417342/178604706-7c119bc7-e9b4-4b57-a629-75fff53a5347.gif)
