### ISSUE TITLE
Remove Java snippets (for annotation).

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#281]
As Java snippets doesn't take care of completion offset, those snippets are displayed anywhere and it can be very annoying
https://plugins.jetbrains.com/plugin/13234-quarkus-tools/reviews#review=47106

We have 2 kinds of Java snippets:

 * snippets to generate full class with import, class, body, methods, etc. I think we could display them only if Java file is empty. See sample at https://github.com/eclipse/lsp4mp/blob/944f5483af90625593f4ba5f2b7e76b78d668427/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/resources/org/eclipse/lsp4mp/snippets/jax-rs.json#L5
 * snippets to generate annotation. I think we should remove them. See sample at https://github.com/eclipse/lsp4mp/blob/944f5483af90625593f4ba5f2b7e76b78d668427/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/resources/org/eclipse/lsp4mp/snippets/mp-metrics.json#L8

@fbricon  @datho7561  @rgrunber  @yeekangc @kathrynkodama what do you think about that?

**Comment by datho7561** [comment]
The completion options for annotations provided by JDT-LS also don't take context into account (i.e. I can add a `@Fallback` annotation within a method). From what I can tell, regular Eclipse with JDT doesn't provide completion proposals for annotations (maybe there is a setting I missed though).

The benefit of the snippets provided by lsp4mp is that they add all the expected parameters to the annotation when you accept them, and allow you to tab through the parameters. I think it makes sense to add this functionality into JDT/JDT-LS, so that when you accept an annotation completion, it inserts all the required parameters. (There is this issue that you submitted @angelozerr https://github.com/eclipse/eclipse.jdt.ls/issues/1860, but I think it should also happen for completion).

Until JDT/JDT-LS provides this support, I think that the annotation snippets in lsp4mp are helpful.

**Comment by rgrunber** [comment]
I agree with @datho7561 here. One thing I liked about the annotation snippets, was that they automatically generate the necessary parameters, and allow you to cycle through them.

**Comment by angelozerr** [comment]
OK thanks for your feedback guys. Perhaps we should provide a settings to disable those snippets because some user complain about that in IJ.

**Comment by angelozerr** [comment]
@jeffmaury what do you think about the settings which disable snippets completion?

**Comment by jeffmaury** [comment]
I don't think this review is relevant anymore

**Comment by angelozerr** [comment]
Since now we show snippets annotations only if the completion is triggered before a method, I close this issue.

See https://github.com/eclipse/lsp4mp/pull/338
