### ISSUE TITLE
When apply @APIResponses, get xml strange pop up

### ISSUE THREAD

**Issue by gkwan-ibm** [eclipse/lsp4mp#324]
when apply `@APIResponses`, `@Parameters`, `@Schema`, and …, get following:

![Screen Shot 2022-11-16 at 12 34 25 PM](https://user-images.githubusercontent.com/29576299/203407130-717c65f5-a5cd-4d4b-9b41-739570f7da3a.png)

**Comment by rgrunber** [comment]
This is what I see returned by LSP4MP as a completion item :

```json
{
	"label": "@APIResponses",
	"kind": 15,
	"detail": "A container for multiple responses from an API operation.",
	"documentation": {
		"kind": "markdown",
		"value": "\n```\n@APIResponses(\n\tvalue = {1\n\t}\n)\n```\n"
	},
	"filterText": "@APIResponses",
	"insertTextFormat": 2,
	"textEdit": {
		"range": {
			"start": {
				"line": 16,
				"character": 4
			},
			"end": {
				"line": 16,
				"character": 12
			}
		},
		"newText": "@APIResponses(\n\tvalue = {$1\n\t}\n)"
	}
}
```

I don't think we add the XML content anywhere, because we produce markdown content. Is it possible Eclipse is generating the HTML content ? If I remember correctly, the hover is based on some kind of web page render.

**Comment by angelozerr** [comment]
@gkwan-ibm  it is an issue for lsp4e project the Eclipse lsp client.

Please create an issue to this project.

**Comment by gkwan-ibm** [comment]
created https://github.com/eclipse/lsp4e/issues/315

**Comment by angelozerr** [comment]
> created https://github.com/eclipse/lsp4e/issues/315

Thanks.
