### ISSUE TITLE
Improve again completion result of microprofile-config.properties

### ISSUE THREAD

**Issue by angelozerr** [eclipse/lsp4mp#410]
Here a sample of completion item result:

```json
{
      "label": "quarkus.management.filter.{*}.matches",
      "kind": 10,
      "filterText": "quarkus.management.filter.${1:key}.matches",
      "textEditText": "quarkus.management.filter.${1:key}.matches=$0",
      "data": {
          "propertyName": "quarkus.management.filter.{*}.matches",
          "uri": "file:///c%3A/Users/azerr/git/quarkus-blast/src/main/resources/application.properties"
      }
  }
```

I think we can improve again the result to have a lower JSON result since completion for microprofile-config.properties can return a lot of items.

It should be nice to return only:

```json
{
      "label": "quarkus.management.filter.{*}.matches",
      "kind": 10,
      "textEditText": "quarkus.management.filter.${1:key}.matches=$0"
  }
```

* filterText can be removed and LSP cient will use label instead which will be better since filterText contains snippet syntax ("filterText": "quarkus.management.filter.${1:key}.matches"
* data/propertyName is the same value than label, so we can remove it and use label.
* data/uri are the same for all completion items, so we can move this information in CompletionItemDefaults/data

@JessicaJHee what do you think about that?

**Comment by JessicaJHee** [comment]
I'm interested in working on this!

**Comment by rgrunber** [comment]
Just something to be aware of because I noticed you mention attempting to de-duplicate `data` fields of a comletion item, https://github.com/eclipse/eclipse.jdt.ls/issues/2621 . So even if `data` were supported ([it isn't for vscode-languageclient](https://github.com/microsoft/vscode-languageserver-node/blob/release/client/8.1.0/client/src/common/completion.ts#L94)), the behaviour is not to merge data fields, but to have the more specific (eg. `item.data` overrides `list.itemDefaults.data`)
