### ISSUE TITLE
Diagnostics for mp fault-tolerance Asynchronous annotation

### ISSUE THREAD

**Issue by rzgry** [eclipse/lsp4mp#74]
https://github.com/eclipse/microprofile-fault-tolerance/blob/master/spec/src/main/asciidoc/asynchronous.asciidoc#asynchronous

Any methods marked with this annotation must return one of:

`java.util.concurrent.Future`
`java.util.concurrent.CompletionStage`
Otherwise, org.eclipse.microprofile.faulttolerance.exceptions.FaultToleranceDefinitionException occurs during deployment.

**Comment by kathrynkodama** [comment]
I can pick this up

**Comment by angelozerr** [comment]
I reopen the issue because according this test https://github.com/eclipse/microprofile-fault-tolerance/blob/e7a1f982b2a0bae837ae99115e8da5e9c67d230b/tck/src/main/java/org/eclipse/microprofile/fault/tolerance/tck/invalidParameters/AsynchronousClientForValidationClass.java#L30,  it seems that @Asynchronous annotation can be set on the class (not only on the methods) and all methods are considered as Asynchronous  (it's my supposition)

@AlexXuChen could you check that in a real application, implement this new usecase and write a test. Thanks!
